elasticsearch:
  build: elasticsearch/
  container_name: es
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  image: kibana:latest
  container_name: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
